#!/usr/bin/env python3
"""codex_parity_sync.py — mirror per-repo Claude assets into Codex's discovery layers.

Codex CLI (0.135) reads project-scoped config only from `.codex/` (trusted projects)
and auto-discovers skills from `.agents/skills/`. It does NOT read `.claude/`. So a
repo whose tooling lives under `.claude/` (skills, hooks) and `.mcp.json` is invisible
to Codex beyond its AGENTS.md.

Source of truth stays in each repo's COMMITTED `.claude/` + `.mcp.json`. This script
generates the Codex-local mirror, which is GITIGNORED (like the already-ignored
`.agents/`) and regenerated by friend-sync:

  <repo>/.codex/config.toml   delta MCP servers (those missing from ~/.codex global,
                              plus explicit intentional overrides) — merges with global
  <repo>/.codex/hooks.json    project hooks from .claude/settings.json, with
                              $CLAUDE_PROJECT_DIR / relative hook paths absolutized so
                              they fire regardless of Codex's session cwd — merges with
                              ~/.codex/hooks.json
  <repo>/.agents/skills       symlink -> <repo>/.claude/skills (Codex auto-discovers)

Empirically verified (2026-06-02, codex-cli 0.135):
  - project .codex/config.toml mcp_servers MERGE with ~/.codex/config.toml (union).
  - project .codex/hooks.json hooks MERGE with ~/.codex/hooks.json (3 SessionStart
    hooks fired = 2 global + 1 project).
  - Codex normalizes hook tool-name matchers to Claude style (Bash, Write|Edit ->
    apply_patch, mcp__server__tool) and uses the same $CLAUDE_TOOL_INPUT / exit-2 /
    additionalContext contract, so Claude project hooks port over.

Run:
  uv run python3 scripts/codex_parity_sync.py            # sync all mirrored repos
  uv run python3 scripts/codex_parity_sync.py --check    # report drift, write nothing
  uv run python3 scripts/codex_parity_sync.py --repo intel
"""
from __future__ import annotations

import argparse
import copy
import json
import os
import re
import shlex
import subprocess
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common.console import con  # noqa: E402
from common.project_registry import MIRRORED_REPOS  # noqa: E402

HOME = Path.home()
PROJECTS = HOME / "Projects"
GLOBAL_CODEX_CONFIG = HOME / ".codex" / "config.toml"

REPOS = list(MIRRORED_REPOS)

# Servers whose .mcp.json definition deliberately differs from the ~/.codex global
# and where the PROJECT one should win (project-scoped override). Everything else
# that merely differs is reported as drift, not silently overridden — global is often
# the newer/canonical definition (e.g. brave-search package rename).
INTENTIONAL_OVERRIDES = {
    "intel": {"duckdb"},  # intel wants motherduck on intel.duckdb, not agent-infra duckdb-mcp
}

LOCAL_PROJECT_MCP = {
    "agent-infra": {
        "agent-infra": {
            "command": "uv",
            "args": ["run", "--directory", str(PROJECTS / "agent-infra"), "agent-infra-mcp"],
        },
        "corpus": {
            "command": "uv",
            "args": ["run", "--directory", str(PROJECTS / "agent-infra"), "corpus-mcp"],
            "env": {
                "CORPUS_ROOT": str(PROJECTS / "corpus"),
                "RESEARCH_MCP_CALLER": "agent-infra",
            },
        },
        "duckdb": {
            "command": "uv",
            "args": ["run", "--directory", str(PROJECTS / "agent-infra"), "duckdb-mcp"],
        },
        "modal-triage": {
            "command": "uv",
            "args": ["run", "--directory", str(PROJECTS / "agent-infra"), "modal-triage-mcp"],
        },
        "parallel": {
            "command": "uv",
            "args": ["run", "--directory", str(PROJECTS / "agent-infra"), "parallel-mcp"],
            "env": {
                "PARALLEL_API_KEY": "${PARALLEL_API_KEY}",
            },
        },
        "perplexity": {
            "command": "npx",
            "args": ["-y", "@perplexity-ai/mcp-server"],
            "startup_timeout_sec": 30.0,
            "tool_timeout_sec": 300,
            "env": {
                "PERPLEXITY_API_KEY": "${PERPLEXITY_API_KEY}",
            },
        },
    },
}

ENV_PLACEHOLDER = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")
FULL_ENV_PLACEHOLDER = re.compile(r"^\$\{([A-Za-z_][A-Za-z0-9_]*)\}$")


# ── TOML emit (stdlib has no writer; our shape is shallow) ──────────────────


def _toml_str(s: str) -> str:
    # JSON string escaping is a valid subset of TOML basic-string escaping for our keys.
    return json.dumps(s)


def _toml_array(items: list[str]) -> str:
    return "[" + ", ".join(_toml_str(x) for x in items) + "]"


def _toml_env_var(item: str | dict[str, str]) -> str:
    if isinstance(item, str):
        return _toml_str(item)
    parts = [f"name = {_toml_str(item['name'])}"]
    if source := item.get("source"):
        parts.append(f"source = {_toml_str(source)}")
    return "{ " + ", ".join(parts) + " }"


def _toml_env_vars(items: list[str | dict[str, str]]) -> str:
    return "[" + ", ".join(_toml_env_var(item) for item in items) + "]"


def _env_var_source(item: str | dict[str, str]) -> str:
    if isinstance(item, str):
        return item
    return item.get("source", item["name"])


def codex_env_fields(spec: dict) -> tuple[dict[str, str], list[str | dict[str, str]]]:
    """Split MCP env into literal env values and Codex env_vars pass-throughs."""
    literal_env: dict[str, str] = {}
    env_vars: list[str | dict[str, str]] = list(spec.get("env_vars") or [])
    for key, value in (spec.get("env") or {}).items():
        if isinstance(value, str) and (match := FULL_ENV_PLACEHOLDER.match(value)):
            source = match.group(1)
            env_vars.append(key if key == source else {"name": key, "source": source})
        else:
            literal_env[str(key)] = str(value)
    return literal_env, env_vars


def missing_required_env(spec: dict) -> list[str]:
    _, env_vars = codex_env_fields(spec)
    return sorted({source for source in map(_env_var_source, env_vars) if not os.environ.get(source)})


def keychain_service(env_var: str) -> str:
    return f"agent-infra/{env_var}"


def keychain_has_secret(env_var: str) -> bool:
    return subprocess.run(
        ["security", "find-generic-password", "-s", keychain_service(env_var), "-w"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    ).returncode == 0


def keychain_wrapped_spec(spec: dict, env_vars: list[str]) -> dict:
    wrapped = copy.deepcopy(spec)
    original_cmd = [str(wrapped["command"]), *map(str, wrapped.get("args") or [])]
    exports = [
        f"export {var}=$(security find-generic-password -s {shlex.quote(keychain_service(var))} -w)"
        for var in env_vars
    ]
    exports.append("exec " + shlex.join(original_cmd))
    wrapped["command"] = "zsh"
    wrapped["args"] = ["-lc", "; ".join(exports)]

    env = {}
    for key, value in (wrapped.get("env") or {}).items():
        if isinstance(value, str) and (match := FULL_ENV_PLACEHOLDER.match(value)) and match.group(1) in env_vars:
            continue
        env[key] = value
    if env:
        wrapped["env"] = env
    else:
        wrapped.pop("env", None)
    return wrapped


def emit_mcp_toml(servers: dict[str, dict]) -> str:
    lines: list[str] = [
        "# GENERATED by agent-infra/scripts/codex_parity_sync.py — do not edit by hand.",
        "# Source of truth: this repo's .mcp.json + ~/.codex/config.toml (global).",
        "# Merges with the global ~/.codex/config.toml mcp_servers (union).",
        "",
    ]
    for sid, spec in sorted(servers.items()):
        lines.append(f"[mcp_servers.{sid}]")
        if "url" in spec:
            lines.append(f"url = {_toml_str(spec['url'])}")
        else:
            lines.append(f"command = {_toml_str(spec['command'])}")
            if spec.get("args"):
                lines.append(f"args = {_toml_array(spec['args'])}")
        for key in ("startup_timeout_sec", "tool_timeout_sec"):
            if key in spec:
                lines.append(f"{key} = {float(spec[key])}")
        env, env_vars = codex_env_fields(spec)
        if env_vars:
            lines.append(f"env_vars = {_toml_env_vars(env_vars)}")
        # env sub-table must come after the parent's scalar keys
        if env:
            lines.append("")
            lines.append(f"[mcp_servers.{sid}.env]")
            for k, v in env.items():
                lines.append(f"{k} = {_toml_str(v)}")
        lines.append("")
    return "\n".join(lines) + "\n"


# ── Loaders ─────────────────────────────────────────────────────────────────


def load_global_mcp() -> dict[str, dict]:
    if not GLOBAL_CODEX_CONFIG.exists():
        return {}
    with open(GLOBAL_CODEX_CONFIG, "rb") as f:
        data = tomllib.load(f)
    return data.get("mcp_servers", {})


def load_project_mcp(repo_dir: Path) -> dict[str, dict]:
    p = repo_dir / ".mcp.json"
    if not p.exists():
        return LOCAL_PROJECT_MCP.get(repo_dir.name, {})
    project = json.loads(p.read_text()).get("mcpServers", {})
    project.update(LOCAL_PROJECT_MCP.get(repo_dir.name, {}))
    return project


def expand_env_placeholders_for_compare(value):
    """Expand ${VAR} placeholders only in-memory for project/global identity checks."""
    if isinstance(value, dict):
        return {k: expand_env_placeholders_for_compare(v) for k, v in value.items()}
    if isinstance(value, list):
        return [expand_env_placeholders_for_compare(v) for v in value]
    if isinstance(value, str):
        def repl(match: re.Match[str]) -> str:
            name = match.group(1)
            return os.environ.get(name, match.group(0))

        return ENV_PLACEHOLDER.sub(repl, value)
    return value


def _sig(spec: dict) -> tuple:
    """Identity for override detection: transport-defining fields only (ignore env/secrets)."""
    if "url" in spec:
        return ("http", spec["url"])
    return ("stdio", spec.get("command"), tuple(spec.get("args", [])))


def _sig_for_compare(spec: dict) -> tuple:
    return _sig(expand_env_placeholders_for_compare(spec))


# ── Per-repo sync steps ───────────────────────────────────────────────────────


def compute_mcp_delta(repo: str, repo_dir: Path) -> tuple[dict[str, dict], list[str]]:
    """Return (servers_to_emit, drift_notes)."""
    project = load_project_mcp(repo_dir)
    glob = load_global_mcp()
    overrides = INTENTIONAL_OVERRIDES.get(repo, set())
    emit: dict[str, dict] = {}
    drift: list[str] = []
    for sid, spec in project.items():
        should_emit = False
        if sid not in glob:
            should_emit = True
        elif _sig_for_compare(spec) != _sig_for_compare(glob[sid]):
            if sid in overrides:
                should_emit = True
            else:
                drift.append(
                    f"{sid}: .mcp.json differs from ~/.codex global "
                    f"(project={_sig_for_compare(spec)} global={_sig_for_compare(glob[sid])}) — not overriding"
                )
        if should_emit:
            missing = missing_required_env(spec)
            if missing:
                if "url" not in spec and all(keychain_has_secret(var) for var in missing):
                    emit[sid] = keychain_wrapped_spec(spec, missing)
                    drift.append(
                        f"{sid}: using Keychain fallback for missing env var(s): {', '.join(missing)}"
                    )
                else:
                    drift.append(
                        f"{sid}: skipped from .codex/config.toml because required env var(s) "
                        f"are missing: {', '.join(missing)}"
                    )
            else:
                emit[sid] = spec
    # Warn on unresolved ${VAR} only where Codex cannot pass through env_vars safely.
    for sid, spec in emit.items():
        env, _ = codex_env_fields(spec)
        blob = json.dumps(env) + spec.get("url", "")
        for m in re.findall(r"\$\{[^}]+\}", blob):
            drift.append(f"{sid}: emitted with unresolved {m} — Codex passes it literally")
    return emit, drift


def absolutize_hook_command(cmd: str, repo_dir: Path) -> str:
    abs_repo = str(repo_dir)
    out = cmd.replace("${CLAUDE_PROJECT_DIR}", abs_repo).replace("$CLAUDE_PROJECT_DIR", abs_repo)
    # Resolve leading relative hook-script invocations to absolute repo paths so they
    # fire regardless of Codex's session cwd. Matches a path token at a command
    # boundary (start, after ;, &&, |, or whitespace) like `.claude/hooks/x.sh` or
    # `scripts/hooks/x.sh`.
    out = re.sub(
        r"(^|[\s;&|])((?:\.claude|scripts)/hooks/[^\s;&|]+)",
        lambda m: f"{m.group(1)}{abs_repo}/{m.group(2)}",
        out,
    )
    return out


CODEX_HOOK_SHIM = Path(__file__).resolve().parent / "codex_hook_shim.py"


def codex_hook_command(cmd: str, repo_dir: Path, event: str) -> str:
    """Wrap a hook command so its output is translated to Codex's contract.

    Claude-dialect hook output (top-level additionalContext, exit-2 reason on
    stdout) is reshaped to Codex's shape (hookSpecificOutput.additionalContext,
    exit-2 reason on stderr) by codex_hook_shim.py at runtime. The hook body and
    the Claude path are untouched. See the shim module for the full contract.
    """
    out = absolutize_hook_command(cmd, repo_dir)
    if "codex_hook_shim" in out:
        return out
    return f"CODEX_HOOK_EVENT={shlex.quote(event)} python3 {shlex.quote(str(CODEX_HOOK_SHIM))} {shlex.quote(out)}"


def transform_hooks(settings_hooks: dict, repo_dir: Path) -> dict:
    out: dict = {}
    for event, matchers in settings_hooks.items():
        new_matchers = []
        for matcher in matchers:
            m = dict(matcher)
            m["hooks"] = [
                {**h, "command": codex_hook_command(h["command"], repo_dir, event)}
                if h.get("type") == "command" and "command" in h
                else h
                for h in matcher.get("hooks", [])
            ]
            new_matchers.append(m)
        out[event] = new_matchers
    return out


def load_project_hooks(repo_dir: Path) -> dict:
    p = repo_dir / ".claude" / "settings.json"
    if not p.exists():
        return {}
    return json.loads(p.read_text()).get("hooks", {})


def ensure_gitignored(repo_dir: Path, entry: str, check: bool) -> bool:
    """Ensure `entry` is in repo .gitignore. Return True if already present/added."""
    gi = repo_dir / ".gitignore"
    existing = gi.read_text().splitlines() if gi.exists() else []
    if any(line.strip().rstrip("/") == entry.rstrip("/") for line in existing):
        return True
    if check:
        return False
    with open(gi, "a") as f:
        if existing and existing[-1].strip():
            f.write("\n")
        f.write(f"{entry}\n")
    return True


def sync_repo(repo: str, check: bool) -> dict:
    repo_dir = PROJECTS / repo
    result = {"repo": repo, "mcp": 0, "hooks": 0, "skills": None, "drift": [], "would_update": 0}
    if not repo_dir.exists():
        con.warn(f"{repo}: repo dir missing — skipped")
        return result
    con.step(repo)

    # 1. MCP delta -> .codex/config.toml
    emit, drift = compute_mcp_delta(repo, repo_dir)
    result["drift"] = drift
    result["mcp"] = len(emit)
    codex_dir = repo_dir / ".codex"
    cfg_path = codex_dir / "config.toml"
    if emit:
        toml_text = emit_mcp_toml(emit)
        if check:
            current = cfg_path.read_text() if cfg_path.exists() else ""
            updated = current != toml_text
            result["would_update"] += int(updated)
            state = "WOULD UPDATE" if updated else "in sync"
            con.kv("mcp delta", f"{', '.join(sorted(emit))} [{state}]")
        else:
            codex_dir.mkdir(exist_ok=True)
            cfg_path.write_text(toml_text)
            con.ok(f"mcp delta -> .codex/config.toml ({', '.join(sorted(emit))})")
    else:
        con.kv("mcp delta", "none (all project servers already global)")

    # 2. Project hooks -> .codex/hooks.json (paths absolutized)
    phooks = load_project_hooks(repo_dir)
    if phooks:
        transformed = {"hooks": transform_hooks(phooks, repo_dir)}
        count = sum(len(h.get("hooks", [])) for ms in transformed["hooks"].values() for h in ms)
        result["hooks"] = count
        hooks_path = codex_dir / "hooks.json"
        new_text = json.dumps(transformed, indent=2) + "\n"
        if check:
            current = hooks_path.read_text() if hooks_path.exists() else ""
            updated = current != new_text
            result["would_update"] += int(updated)
            state = "WOULD UPDATE" if updated else "in sync"
            con.kv("hooks", f"{count} project hooks [{state}]")
        else:
            codex_dir.mkdir(exist_ok=True)
            hooks_path.write_text(new_text)
            con.ok(f"{count} project hooks -> .codex/hooks.json (merges with global)")
    else:
        con.kv("hooks", "no project hooks in .claude/settings.json")

    # 3. Skills symlink .agents/skills -> .claude/skills
    claude_skills = repo_dir / ".claude" / "skills"
    agents_skills = repo_dir / ".agents" / "skills"
    if claude_skills.is_dir():
        want = claude_skills
        have = agents_skills.is_symlink() and agents_skills.resolve() == want.resolve()
        result["skills"] = have
        if have:
            con.kv("skills", ".agents/skills -> .claude/skills (ok)")
        elif check:
            con.kv("skills", ".agents/skills MISSING — would link")
        else:
            (repo_dir / ".agents").mkdir(exist_ok=True)
            if agents_skills.exists() or agents_skills.is_symlink():
                agents_skills.unlink()
            agents_skills.symlink_to(want)
            result["skills"] = True
            con.ok(".agents/skills -> .claude/skills (linked)")
    else:
        con.kv("skills", "no .claude/skills dir")

    # 4. gitignore .codex/ (and confirm .agents/ already ignored)
    for entry in (".codex/", ".agents/"):
        present = ensure_gitignored(repo_dir, entry, check)
        if not present:
            con.warn(f"{entry} not in .gitignore" + (" (would add)" if check else ""))

    for d in drift:
        con.warn(f"divergence (info): {d}")
    return result


def main() -> int:
    ap = argparse.ArgumentParser(description="Mirror Claude project assets into Codex layers.")
    ap.add_argument("--repo", action="append", choices=REPOS, help="limit to repo(s)")
    ap.add_argument("--check", action="store_true", help="report drift, write nothing")
    args = ap.parse_args()

    con.header("Codex parity sync" + (" (check)" if args.check else ""))
    repos = args.repo or REPOS
    results = [sync_repo(r, args.check) for r in repos]

    con.header("Summary")
    total_div = 0
    total_stale = 0
    for r in results:
        skill_state = "none" if r["skills"] is None else ("✓" if r["skills"] else "✗")
        con.kv(
            r["repo"],
            f"mcp+{r['mcp']}  hooks={r['hooks']}  skills={skill_state}"
            + (f"  divergences={len(r['drift'])}" if r["drift"] else ""),
        )
        total_div += len(r["drift"])
        total_stale += r["would_update"]
    if args.check and total_stale:
        con.warn(f"{total_stale} file(s) out of sync — run without --check to regenerate")
    elif args.check:
        con.ok("all .codex/ mirrors in sync")
    if total_div:
        con.kv("divergences", f"{total_div} project↔global .mcp.json diffs (informational, not overridden)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
