#!/usr/bin/env python3
"""codex_parity_sync.py — mirror per-repo Claude assets into Codex's discovery layers.

Codex CLI (0.135) reads project-scoped config only from `.codex/` (trusted projects)
and auto-discovers skills from `.agents/skills/`. It does NOT read `.claude/`. So a
repo whose tooling lives under `.claude/` (skills, hooks) and `.mcp.json` is invisible
to Codex beyond its AGENTS.md.

Source of truth stays in each repo's COMMITTED `.claude/` + `.mcp.json`. This script
generates the Codex-local mirror, which is GITIGNORED (like the already-ignored
`.agents/`) and regenerated by friend-sync:

  <repo>/.codex/config.toml   delta MCP servers (those missing from ~/.codex global,
                              plus explicit intentional overrides) — merges with global
  <repo>/.codex/hooks.json    project hooks from .claude/settings.json, with
                              $CLAUDE_PROJECT_DIR / relative hook paths absolutized so
                              they fire regardless of Codex's session cwd — merges with
                              ~/.codex/hooks.json
  <repo>/.agents/skills       symlink -> <repo>/.claude/skills (Codex auto-discovers)

Empirically verified (2026-06-02, codex-cli 0.135):
  - project .codex/config.toml mcp_servers MERGE with ~/.codex/config.toml (union).
  - project .codex/hooks.json hooks MERGE with ~/.codex/hooks.json (3 SessionStart
    hooks fired = 2 global + 1 project).
  - Codex normalizes hook tool-name matchers to Claude style (Bash, Write|Edit ->
    apply_patch, mcp__server__tool) and uses the same $CLAUDE_TOOL_INPUT / exit-2 /
    additionalContext contract, so Claude project hooks port over.

Run:
  uv run python3 scripts/codex_parity_sync.py            # sync all mirrored repos
  uv run python3 scripts/codex_parity_sync.py --check    # report drift, write nothing
  uv run python3 scripts/codex_parity_sync.py --repo intel
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common.console import con  # noqa: E402

HOME = Path.home()
PROJECTS = HOME / "Projects"
GLOBAL_CODEX_CONFIG = HOME / ".codex" / "config.toml"

REPOS = ["agent-infra", "intel", "genomics", "phenome"]

# Servers whose .mcp.json definition deliberately differs from the ~/.codex global
# and where the PROJECT one should win (project-scoped override). Everything else
# that merely differs is reported as drift, not silently overridden — global is often
# the newer/canonical definition (e.g. brave-search package rename).
INTENTIONAL_OVERRIDES = {
    "intel": {"duckdb"},  # intel wants motherduck on intel.duckdb, not agent-infra duckdb-mcp
}

LOCAL_PROJECT_MCP = {
    "agent-infra": {
        "agent-infra": {
            "command": "uv",
            "args": ["run", "--directory", str(PROJECTS / "agent-infra"), "agent-infra-mcp"],
        },
        "corpus": {
            "command": "uv",
            "args": ["run", "--directory", str(PROJECTS / "agent-infra"), "corpus-mcp"],
            "env": {
                "CORPUS_ROOT": str(PROJECTS / "corpus"),
                "RESEARCH_MCP_CALLER": "agent-infra",
            },
        },
        "duckdb": {
            "command": "uv",
            "args": ["run", "--directory", str(PROJECTS / "agent-infra"), "duckdb-mcp"],
        },
        "modal-triage": {
            "command": "uv",
            "args": ["run", "--directory", str(PROJECTS / "agent-infra"), "modal-triage-mcp"],
        },
        "parallel": {
            "command": "uv",
            "args": ["run", "--directory", str(PROJECTS / "agent-infra"), "parallel-mcp"],
            "env": {
                "PARALLEL_API_KEY": "${PARALLEL_API_KEY}",
            },
        },
    },
}

SECRET_HINT = re.compile(r"(?:\$\{[^}]+\}|[A-Za-z0-9_-]{24,})")


# ── TOML emit (stdlib has no writer; our shape is shallow) ──────────────────


def _toml_str(s: str) -> str:
    # JSON string escaping is a valid subset of TOML basic-string escaping for our keys.
    return json.dumps(s)


def _toml_array(items: list[str]) -> str:
    return "[" + ", ".join(_toml_str(x) for x in items) + "]"


def emit_mcp_toml(servers: dict[str, dict]) -> str:
    lines: list[str] = [
        "# GENERATED by agent-infra/scripts/codex_parity_sync.py — do not edit by hand.",
        "# Source of truth: this repo's .mcp.json + ~/.codex/config.toml (global).",
        "# Merges with the global ~/.codex/config.toml mcp_servers (union).",
        "",
    ]
    for sid, spec in sorted(servers.items()):
        lines.append(f"[mcp_servers.{sid}]")
        if "url" in spec:
            lines.append(f"url = {_toml_str(spec['url'])}")
        else:
            lines.append(f"command = {_toml_str(spec['command'])}")
            if spec.get("args"):
                lines.append(f"args = {_toml_array(spec['args'])}")
        env = spec.get("env") or {}
        # env sub-table must come after the parent's scalar keys
        if env:
            lines.append("")
            lines.append(f"[mcp_servers.{sid}.env]")
            for k, v in env.items():
                lines.append(f"{k} = {_toml_str(v)}")
        lines.append("")
    return "\n".join(lines) + "\n"


# ── Loaders ─────────────────────────────────────────────────────────────────


def load_global_mcp() -> dict[str, dict]:
    if not GLOBAL_CODEX_CONFIG.exists():
        return {}
    with open(GLOBAL_CODEX_CONFIG, "rb") as f:
        data = tomllib.load(f)
    return data.get("mcp_servers", {})


def load_project_mcp(repo_dir: Path) -> dict[str, dict]:
    p = repo_dir / ".mcp.json"
    if not p.exists():
        return resolve_env_placeholders(LOCAL_PROJECT_MCP.get(repo_dir.name, {}))
    project = json.loads(p.read_text()).get("mcpServers", {})
    project.update(LOCAL_PROJECT_MCP.get(repo_dir.name, {}))
    return resolve_env_placeholders(project)


def resolve_env_placeholders(value):
    """Expand ${VAR} placeholders before writing Codex TOML.

    Codex does not expand TOML env values; it passes placeholders literally.
    Project `.mcp.json` files can keep placeholders as source of truth, while
    generated `.codex/config.toml` gets the concrete process environment value.
    """
    if isinstance(value, dict):
        return {k: resolve_env_placeholders(v) for k, v in value.items()}
    if isinstance(value, list):
        return [resolve_env_placeholders(v) for v in value]
    if isinstance(value, str):
        def repl(match: re.Match[str]) -> str:
            name = match.group(1)
            return os.environ.get(name, match.group(0))

        return re.sub(r"\$\{([^}]+)\}", repl, value)
    return value


def _sig(spec: dict) -> tuple:
    """Identity for override detection: transport-defining fields only (ignore env/secrets)."""
    if "url" in spec:
        return ("http", spec["url"])
    return ("stdio", spec.get("command"), tuple(spec.get("args", [])))


# ── Per-repo sync steps ───────────────────────────────────────────────────────


def compute_mcp_delta(repo: str, repo_dir: Path) -> tuple[dict[str, dict], list[str]]:
    """Return (servers_to_emit, drift_notes)."""
    project = load_project_mcp(repo_dir)
    glob = load_global_mcp()
    overrides = INTENTIONAL_OVERRIDES.get(repo, set())
    emit: dict[str, dict] = {}
    drift: list[str] = []
    for sid, spec in project.items():
        if sid not in glob:
            emit[sid] = spec
        elif _sig(spec) != _sig(glob[sid]):
            if sid in overrides:
                emit[sid] = spec
            else:
                drift.append(
                    f"{sid}: .mcp.json differs from ~/.codex global "
                    f"(project={_sig(spec)} global={_sig(glob[sid])}) — not overriding"
                )
    # Warn on unresolved ${VAR} in emitted servers (Codex won't expand config.toml vars).
    for sid, spec in emit.items():
        blob = json.dumps(spec.get("env", {})) + spec.get("url", "")
        for m in re.findall(r"\$\{[^}]+\}", blob):
            drift.append(f"{sid}: emitted with unresolved {m} — Codex passes it literally")
    return emit, drift


def absolutize_hook_command(cmd: str, repo_dir: Path) -> str:
    abs_repo = str(repo_dir)
    out = cmd.replace("${CLAUDE_PROJECT_DIR}", abs_repo).replace("$CLAUDE_PROJECT_DIR", abs_repo)
    # Resolve leading relative hook-script invocations to absolute repo paths so they
    # fire regardless of Codex's session cwd. Matches a path token at a command
    # boundary (start, after ;, &&, |, or whitespace) like `.claude/hooks/x.sh` or
    # `scripts/hooks/x.sh`.
    out = re.sub(
        r"(^|[\s;&|])((?:\.claude|scripts)/hooks/[^\s;&|]+)",
        lambda m: f"{m.group(1)}{abs_repo}/{m.group(2)}",
        out,
    )
    return out


def transform_hooks(settings_hooks: dict, repo_dir: Path) -> dict:
    out: dict = {}
    for event, matchers in settings_hooks.items():
        new_matchers = []
        for matcher in matchers:
            m = dict(matcher)
            m["hooks"] = [
                {**h, "command": absolutize_hook_command(h["command"], repo_dir)}
                if h.get("type") == "command" and "command" in h
                else h
                for h in matcher.get("hooks", [])
            ]
            new_matchers.append(m)
        out[event] = new_matchers
    return out


def load_project_hooks(repo_dir: Path) -> dict:
    p = repo_dir / ".claude" / "settings.json"
    if not p.exists():
        return {}
    return json.loads(p.read_text()).get("hooks", {})


def ensure_gitignored(repo_dir: Path, entry: str, check: bool) -> bool:
    """Ensure `entry` is in repo .gitignore. Return True if already present/added."""
    gi = repo_dir / ".gitignore"
    existing = gi.read_text().splitlines() if gi.exists() else []
    if any(line.strip().rstrip("/") == entry.rstrip("/") for line in existing):
        return True
    if check:
        return False
    with open(gi, "a") as f:
        if existing and existing[-1].strip():
            f.write("\n")
        f.write(f"{entry}\n")
    return True


def sync_repo(repo: str, check: bool) -> dict:
    repo_dir = PROJECTS / repo
    result = {"repo": repo, "mcp": 0, "hooks": 0, "skills": False, "drift": [], "would_update": 0}
    if not repo_dir.exists():
        con.warn(f"{repo}: repo dir missing — skipped")
        return result
    con.step(repo)

    # 1. MCP delta -> .codex/config.toml
    emit, drift = compute_mcp_delta(repo, repo_dir)
    result["drift"] = drift
    result["mcp"] = len(emit)
    codex_dir = repo_dir / ".codex"
    cfg_path = codex_dir / "config.toml"
    if emit:
        toml_text = emit_mcp_toml(emit)
        if check:
            current = cfg_path.read_text() if cfg_path.exists() else ""
            updated = current != toml_text
            result["would_update"] += int(updated)
            state = "WOULD UPDATE" if updated else "in sync"
            con.kv("mcp delta", f"{', '.join(sorted(emit))} [{state}]")
        else:
            codex_dir.mkdir(exist_ok=True)
            cfg_path.write_text(toml_text)
            con.ok(f"mcp delta -> .codex/config.toml ({', '.join(sorted(emit))})")
    else:
        con.kv("mcp delta", "none (all project servers already global)")

    # 2. Project hooks -> .codex/hooks.json (paths absolutized)
    phooks = load_project_hooks(repo_dir)
    if phooks:
        transformed = {"hooks": transform_hooks(phooks, repo_dir)}
        count = sum(len(h.get("hooks", [])) for ms in transformed["hooks"].values() for h in ms)
        result["hooks"] = count
        hooks_path = codex_dir / "hooks.json"
        new_text = json.dumps(transformed, indent=2) + "\n"
        if check:
            current = hooks_path.read_text() if hooks_path.exists() else ""
            updated = current != new_text
            result["would_update"] += int(updated)
            state = "WOULD UPDATE" if updated else "in sync"
            con.kv("hooks", f"{count} project hooks [{state}]")
        else:
            codex_dir.mkdir(exist_ok=True)
            hooks_path.write_text(new_text)
            con.ok(f"{count} project hooks -> .codex/hooks.json (merges with global)")
    else:
        con.kv("hooks", "no project hooks in .claude/settings.json")

    # 3. Skills symlink .agents/skills -> .claude/skills
    claude_skills = repo_dir / ".claude" / "skills"
    agents_skills = repo_dir / ".agents" / "skills"
    if claude_skills.is_dir():
        want = claude_skills
        have = agents_skills.is_symlink() and agents_skills.resolve() == want.resolve()
        result["skills"] = have
        if have:
            con.kv("skills", ".agents/skills -> .claude/skills (ok)")
        elif check:
            con.kv("skills", ".agents/skills MISSING — would link")
        else:
            (repo_dir / ".agents").mkdir(exist_ok=True)
            if agents_skills.exists() or agents_skills.is_symlink():
                agents_skills.unlink()
            agents_skills.symlink_to(want)
            result["skills"] = True
            con.ok(".agents/skills -> .claude/skills (linked)")
    else:
        con.kv("skills", "no .claude/skills dir")

    # 4. gitignore .codex/ (and confirm .agents/ already ignored)
    for entry in (".codex/", ".agents/"):
        present = ensure_gitignored(repo_dir, entry, check)
        if not present:
            con.warn(f"{entry} not in .gitignore" + (" (would add)" if check else ""))

    for d in drift:
        con.warn(f"divergence (info): {d}")
    return result


def main() -> int:
    ap = argparse.ArgumentParser(description="Mirror Claude project assets into Codex layers.")
    ap.add_argument("--repo", action="append", choices=REPOS, help="limit to repo(s)")
    ap.add_argument("--check", action="store_true", help="report drift, write nothing")
    args = ap.parse_args()

    con.header("Codex parity sync" + (" (check)" if args.check else ""))
    repos = args.repo or REPOS
    results = [sync_repo(r, args.check) for r in repos]

    con.header("Summary")
    total_div = 0
    total_stale = 0
    for r in results:
        con.kv(
            r["repo"],
            f"mcp+{r['mcp']}  hooks={r['hooks']}  skills={'✓' if r['skills'] else '✗'}"
            + (f"  divergences={len(r['drift'])}" if r["drift"] else ""),
        )
        total_div += len(r["drift"])
        total_stale += r["would_update"]
    if args.check and total_stale:
        con.warn(f"{total_stale} file(s) out of sync — run without --check to regenerate")
    elif args.check:
        con.ok("all .codex/ mirrors in sync")
    if total_div:
        con.kv("divergences", f"{total_div} project↔global .mcp.json diffs (informational, not overridden)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
